#!/bin/bash

Mouse=`xinput list | grep -i TouchPad | awk -F= '{ print $2}' | awk '{print $1}' | awk 'BEGIN{ RS = "" ; FS = "\n" }{print $1}'`

xinput set-prop $Mouse "Device Enabled" 0

Mouse=`xinput list | grep -i Stick | awk -F= '{ print $2}' | awk '{print $1}' | awk 'BEGIN{ RS = "" ; FS = "\n" }{print $1}'`

xinput set-float-prop $Mouse "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1.5
